version: '3'

services:
  backend:
    build: ../
    ports:
      - 3001:3001
    environment:
     - DB_HOST="localhost"
     - DB_USER="hps"
     - DB_PORT="3306"
     - DB_PASSWORD="heldersantigo273@""
     - DB_NAME="papDB"
     - JWT_SECRET_KEY=aSHjeq7872bdbbDJJDH378884377Jj@@jhd777bshsh
    volumes:
      - ../:/app-pap-backend
    container_name: PAP-BACKEND
    restart: always
